regsvr32 "\\Bhl-data\srfiles$\DATA_Inviroment.dll"
regsvr32 "\\Bhl-data\srfiles$\PayRollDll.dll"
regsvr32 "\\Bhl-data\srfiles$\sj_web_cam.ocx"
regsvr32 "\\Bhl-data\srfiles$\swflash.ocx"
regsvr32 "\\Bhl-data\srfiles$\InvestigationDll.dll"